#import "SCIDefaults.h"
#import "Utils.h"
#import "UI/Notification/SCINotificationCenter.h"

NSDictionary *SCIDefaultsDictionary(void) {
	return @{
		@"hide_ads": @(YES),
		@"copy_description": @(YES),
		@"profile_copy_button": @(YES),
		@"detailed_color_picker": @(YES),
		@"remove_screenshot_alert": @(YES),
		@"voice_call_confirm": @(NO),
		@"video_call_confirm": @(NO),
		@"keep_deleted_message": @(NO),
		@"deleted_messages_log_enabled": @(NO),
		@"dm_log_date_format": @"relative",
		@"hide_suggested_stories": @(NO),
		@"hide_stories_midcards": @(NO),
		@"profile_analyzer_accumulate": @(NO),
		@"profile_analyzer_track_visits": @(NO),
		@"story_tray_actions": @(NO),
		@"zoom_profile_photo": @(NO),
		@"follow_indicator": @"off",
		@"profile_note_copy": @(NO),
		@"disable_disappearing_mode_swipe": @(NO),
		@"hide_voice_call_button": @(NO),
		@"hide_video_call_button": @(NO),
		@"fake_location_enabled": @(NO),
		@"show_fake_location_map_button": @(NO),
		@"fake_location_lat": @(48.8584),
		@"fake_location_lon": @(2.2945),
		@"fake_location_name": @"Eiffel Tower",
		@"fake_location_presets": @[],
		@"messages_only": @(NO),
		@"messages_only_hide_tabbar": @(NO),
		@"hide_send_to_group": @(NO),
		@"confirm_send_to_group": @(NO),
		@"share_sheet_pin_threads": @(NO),
		@"share_sheet_pinned_thread_ids": @[],
		@"hide_reels_friends_bubbles": @(NO),
		@"hide_reels_floating_social_context": @(NO),
		@"hide_made_with_edits": @(NO),
		@"full_followers_count": @(NO),
		@"full_posts_count": @(NO),
		@"fake_follower_count": @(NO),
		@"fake_following_count": @(NO),
		@"fake_post_count": @(NO),
		@"fake_verified": @(NO),
		@"launch_tab": @"default",
		@"save_profile": @(YES),

		@"liquid_glass_buttons": @(NO),
		@"liquid_glass_surfaces": @(NO),

		@"flex_app_launch": @(NO),
		@"flex_app_start": @(NO),
		@"flex_instagram": @(NO),

		@"hide_stories_tray": @(NO),
		@"hide_meta_ai": @(NO),
		@"hide_entire_feed": @(NO),
		@"hide_explore_grid": @(NO),
		@"hide_explore_tab": @(NO),
		@"hide_feed_tab": @(NO),
		@"hide_reels_tab": @(NO),
		@"hide_messages_tab": @(NO),
		@"hide_create_tab": @(NO),
		@"hide_friends_map": @(NO),
		@"hide_metrics": @(NO),
		@"hide_reels_blend": @(NO),
		@"hide_reels_header": @(NO),
		@"hide_trending_searches": @(NO),
		@"no_suggested_users": @(NO),
		@"no_suggested_chats": @(NO),
		@"no_suggested_threads": @(NO),
		@"no_suggested_reels": @(NO),
		@"no_suggested_post": @(NO),
		@"no_suggested_account": @(NO),
		@"no_recent_searches": @(NO),
		@"no_seen_receipt": @(NO),
		@"remove_lastseen": @(NO),

		@"like_confirm": @(NO),
		@"like_confirm_reels": @(NO),
		@"note_like_confirm": @(NO),
		@"note_react_confirm": @(NO),
		@"follow_confirm": @(NO),
		@"follow_request_confirm": @(NO),
		@"post_comment_confirm": @(NO),
		@"refresh_reel_confirm": @(NO),
		@"shh_mode_confirm": @(NO),
		@"voice_message_confirm": @(NO),
		@"change_direct_theme_confirm": @(NO),

		@"disable_feed_autoplay": @(NO),
		@"disable_haptics": @(NO),
		@"disable_instants_creation": @(NO),
		@"disable_scrolling_reels": @(NO),
		@"disable_typing_status": @(NO),
		@"disable_view_once_limitations": @(NO),
		@"enable_hidden_texteffectsstyles": @(NO),
		@"reels_show_scrubber": @(NO),
		@"stop_story_auto_advance": @(NO),
		@"unlimited_replay": @(NO),
		@"teen_app_icons": @(NO),
		@"sci_exp_flags_enabled": @(NO),

		@"feed_media_zoom": @(NO),
		@"media_zoom_start_muted": @(NO),
		@"enhanced_media_resolution": @(NO),
		@"disable_bg_refresh": @(NO),
		@"disable_home_refresh": @(NO),
		@"disable_home_scroll": @(NO),
		@"main_feed_mode": @"default",
		@"disable_reels_tab_refresh": @(NO),
		@"dm_full_last_active": @(NO),
		@"bypass_dm_char_limit": @(NO),
		@"send_file": @(NO),
		@"note_actions": @(NO),
		@"note_copy_on_hold": @(NO),
		@"feed_date_format": @"default",
		@"feed_date_show_seconds": @(NO),
		@"feed_date_relative_days_threshold": @(0),
		@"feed_date_compact_relative": @(NO),
		@"feed_date_append_relative": @(NO),

		@"date_fmt_mixed": @(YES),
		@"date_fmt_notes_comments_stories": @(NO),
		@"date_fmt_dms": @(NO),

		@"feed_action_button": @(YES),
		@"feed_action_default": @"menu",
		@"menu_date_feed": @(NO),
		@"reels_action_button": @(YES),
		@"reels_action_default": @"menu",
		@"menu_date_reels": @(NO),
		@"stories_action_button": @(YES),
		@"stories_action_default": @"menu",
		@"menu_date_stories": @(NO),
		@"dm_visual_action_button": @(YES),
		@"dm_visual_action_default": @"menu",
		@"action_button_icon": @"ellipsis.circle",

		@"action_menu_cfg_feed": @{},
		@"action_menu_cfg_reels": @{},
		@"action_menu_cfg_stories": @{},
		@"action_menu_cfg_dm": @{},
		@"action_menu_cfg_profile": @{},

		@"action_button_profile_enabled": @(NO),
		@"action_button_profile_default_action": @"menu",
		@"action_button_profile_default_copy_info_action": @"copy_username",

		@"sci_gallery_enabled": @(NO),
		@"gallery_save_mode": @"off",
		@"gallery_sort_mode": @(0),
		@"gallery_view_mode": @(0),
		@"show_favorites_at_top": @(NO),
		@"dm_tab_long_press_gallery": @(NO),

		@"home_shortcut_enabled": @(NO),
		@"home_shortcut_icon": @"auto",
		@"home_shortcut_actions": @[],
		@"dm_visual_seen_button": @(YES),
		@"dm_visual_audio_toggle": @(NO),

		@"dw_legacy_gesture": @(NO),
		@"dw_confirm": @(NO),
		@"enhance_download_quality": @(YES),
		@"default_video_quality": @"always_ask",
		@"default_photo_quality": @"high",
		@"ffmpeg_encoding_speed": @"ultrafast",
		@"unfollow_confirm": @(NO),
		@"sticker_interact_stories_mode": @"off",
		@"sticker_interact_highlights_mode": @"off",
		@"dw_save_action": @"share",
		@"dw_finger_count": @(3),
		@"dw_finger_duration": @(0.5),

		@"reels_tap_control": @"default",
		@"reels_photo_tap_mute": @(NO),
		@"nav_icon_ordering": @"default",
		@"swipe_nav_tabs": @"default",
		@"enable_notes_customization": @(YES),
		@"custom_note_themes": @(YES),
		@"disable_auto_unmuting_reels": @(NO),
		@"auto_scroll_reels_mode": @"off",
		@"settings_shortcut": @(YES),
		@"prevent_doom_scrolling": @(NO),
		@"doom_scrolling_reel_count": @(1),

		@"keep_seen_visual_local": @(NO),
		@"send_audio_as_file": @(YES),
		@"download_audio_message": @(NO),
		@"audio_page_download": @(NO),
		@"save_to_ryukgram_album": @(NO),
		@"unlock_password_reels": @(YES),

		@"seen_mode": @"button",
		@"seen_auto_on_interact": @(NO),
		@"seen_auto_on_typing": @(NO),
		@"seen_on_story_like": @(NO),
		@"seen_on_story_reply": @(NO),
		@"advance_on_story_reply": @(NO),
		@"advance_on_mark_seen": @(NO),
		@"advance_on_story_like": @(NO),

		@"indicate_unsent_messages": @(NO),
		@"unsent_message_toast": @(NO),
		@"warn_refresh_clears_preserved": @(NO),

		@"enable_chat_exclusions": @(YES),
		@"chat_blocking_mode": @"block_all",
		@"exclusions_default_keep_deleted": @(NO),
		@"chat_quick_list_button": @(YES),

		@"enable_story_user_exclusions": @(YES),
		@"story_blocking_mode": @"block_all",
		@"story_excluded_show_unexclude_eye": @(YES),
		@"story_seen_mode": @"button",
		@"story_audio_toggle": @(NO),
		@"view_story_mentions": @(YES),
		@"story_mentions_button": @(NO),
		@"story_mentions_counter": @(NO),

		@"stories_show_quiz_answer": @(NO),
		@"stories_show_poll_votes_count": @(NO),
		@"reels_show_quiz_answer": @(NO),
		@"reels_show_poll_votes_count": @(NO),
		@"force_enable_quiz_sticker": @(NO),
		@"bypass_reveal_sticker": @(NO),
		@"photo_sticker_allow_video": @(NO),

		@"sci_fix_duplicate_notifications": @(YES),

		@"settings_pause_playback": @(YES),
		@"embed_links": @(NO),
		@"embed_link_domain": @"kkinstagram.com",
		@"strip_tracking_params": @(NO),
		@"download_highlight_cover": @(YES),
		@"open_links_external": @(NO),
		@"strip_browser_tracking": @(NO),

		@"hide_feed_repost": @(NO),
		@"copy_comment": @(YES),
		@"download_gif_comment": @(YES),
		@"custom_gif_comment": @(NO),
		@"skip_sensitive_content": @(NO),

		@"cache_auto_clear_mode": @"off",
		@"cache_auto_check_size": @(YES),
		@"cache_preserve_messages_db": @(YES),
		@"sci_changelog_force_show": @(NO),

		@"live_anonymous_view": @(NO),
		@"live_hide_comments": @(NO),
		@"hide_ui_on_capture": @(NO),
		@"paste_link_from_search": @(NO),
		@"sci_language": @"system",

		@"theme_mode": @"off",
		@"theme_force": @(NO),
		@"theme_oled_chat": @(NO),
		@"theme_keyboard": @"off",

		@"igt_homecoming": @(NO),
		@"igt_quicksnap": @(NO),
		@"igt_prism": @(NO),
		@"igt_directnotes_friendmap": @(NO),
		@"igt_directnotes_audio_reply": @(NO),
		@"igt_directnotes_avatar_reply": @(NO),
		@"igt_directnotes_gifs_reply": @(NO),
		@"igt_directnotes_photo_reply": @(NO),
		@"sci_exp_warning_seen": @(NO),
		@"custom_music_sticker_color": @(NO),
		@"instants_send_from_gallery": @(NO),
		@"instants_allow_screenshot": @(NO),
		@"instants_download_btn": @(NO),
		@"instants_emoji_reaction_confirm": @(NO),

		@"notif_master_enabled": @(YES),
		@"notif_style": @"colorful",
		@"notif_position": @"top",
		@"notif_default_surface": @"pill",
		@"notif_max_visible": @(2),
		@"notif_haptics": @(YES),
		@"notif_duration": @(1.0),
	};
}

void SCIRegisterDefaultsOnce(void) {
	static dispatch_once_t onceToken;
	dispatch_once(&onceToken, ^{
		NSMutableDictionary *defaults = [SCIDefaultsDictionary() mutableCopy];
		[defaults addEntriesFromDictionary:[SCINotificationCenter defaultPerActionPrefs]];
		[[NSUserDefaults standardUserDefaults] registerDefaults:defaults];
		[SCIUtils setSciRegisteredDefaults:defaults];
	});
}
